pipeline:
  run-tests:
    image: docker.force.fm/msa/python-test:3.6.4
    commands:
      - pip install -r requirements/dev.txt
      - pytest . --tb=line --cov=drf_metadata
      - python setup.py sdist bdist_wheel
      - python setup.py install  # check setup.py is valid

  notify-users-with-telegram:
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
      event: [ push, tag, deployment, pull_request ]

    secrets:
      - source: telegram_api_token
        target: telegram_token
      - source: telegram_receivers
        target: telegram_to
